name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps and expected vs actual.
      placeholder: "1) ...\n2) ...\nExpected: ...\nActual: ..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App version / commit
  - type: dropdown
    id: db
    attributes:
      label: Database
      options: [PostgreSQL, MySQL, SQLite, Other]
